version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --prefix frontend ci
  build:
    commands:
      - npm --prefix frontend run build
  post_build:
    commands:
      - aws s3 sync frontend/dist s3://$FRONTEND_BUCKET --delete
artifacts:
  files:
    - '**/*'
  discard-paths: yes
env:
  parameter-store:
    FRONTEND_BUCKET: "/automation/${ENV}/frontend_bucket"