version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --prefix frontend ci
  build:
    commands:
      - npm --prefix frontend run build
  post_build:
    commands:
      - aws s3 sync frontend/dist s3://$FRONTEND_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
artifacts:
  files:
    - '**/*'
  discard-paths: yes
env:
  parameter-store:
    FRONTEND_BUCKET: "/automation/${ENV}/frontend_bucket"
    CF_DIST_ID: "/automation/${ENV}/frontend_distribution_id"